version: '3.7'

services:
  dm_db:
    image: postgres:10.1-alpine
      # Они определяют, что данные из временной структуры — контейнера будут сохраняться на хост машине.
      # Содержимое /var/lib/postgresql/data/ в postgres_data. !!! Эта информация будет изменена при
      # жизни контейнера и останется на хост машине после его удаления.
      # После удаления контейнера ПО не остается, данные же могут использоваться в будущем
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: alfa_bank
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: Romandeko2003
  dm_web:
    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    build: .
    # Команда, которую нужно запустить после создания образа.
    command:  bash -c "python /Users/aleks/alfa-bank/manage.py migrate --noinput &&
              python /Users/aleks/alfa-bank/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Users/aleks/alfa-bank
    # применяется следующая конструкция: [порт компьютера]:[порт контейнера]
    ports:
      - 8000:8000
      # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис,
      # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
      # Нам нужно, чтобы сервис 'web' дождался бы готовности к работе сервиса 'db'.
    depends_on:
      - dm_db

volumes:
  postgres_data:


