# Generated by Django 4.0.3 on 2022-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_banking', '0011_alter_transfer_from_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='time',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=12),
        ),
    ]
