# Generated by Django 4.0.3 on 2022-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_banking', '0014_remove_reviews_account_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Текущее время'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Напишите ваш отзыв '),
        ),
    ]
