# Generated by Django 4.0.3 on 2022-04-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(default='root', max_length=130),
        ),
    ]
